# Generated by Django 4.2.2 on 2023-07-01 05:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import helpers.upload_files


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('MOBILE PHONES', 'Mobile Phones'), ('COMPUTERS', 'Computers'), ('ELECTRONICS', 'Electronics'), ('HOME_APPLIANCES', 'Home Appliances'), ('SECURITY', 'Security'), ('AUTOMOBILES', 'Automobiles'), ('FURNITURE', 'Furniture'), ('CLOTHING', 'Clothing'), ('SHOES', 'Shoes'), ('ACCESSORIES', 'Accessories'), ('SPORT', 'Sport'), ('FOOD', 'Food')], max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('other', models.CharField(blank=True, max_length=155, null=True)),
                ('origin', models.CharField(max_length=200)),
                ('certification', models.CharField(blank=True, max_length=155, null=True)),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.brand')),
            ],
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(blank=True, choices=[('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL'), ('BIG', 'big'), ('SMOL', 'small')], max_length=40, null=True)),
                ('other_size', models.CharField(blank=True, max_length=40, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Types',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('count', models.DecimalField(decimal_places=1, max_digits=8)),
                ('currency', models.CharField(choices=[('amd', 'AMD'), ('usd', 'USD'), ('rub', 'RUB'), ('yuan', 'YUAN')], max_length=25)),
                ('description', models.TextField(blank=True, null=True)),
                ('size', models.CharField(blank=True, choices=[('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL'), ('BIG', 'big'), ('SMOL', 'small')], max_length=50, null=True)),
                ('color', models.CharField(blank=True, max_length=50, null=True)),
                ('rate', models.DecimalField(decimal_places=1, max_digits=2)),
                ('photo', models.ImageField(upload_to=helpers.upload_files.upload_product_image)),
                ('video', models.FileField(blank=True, null=True, upload_to='videos/')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('categories', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.categories')),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.character', verbose_name='Characteristics')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
