# Generated by Django 4.2.2 on 2023-07-06 22:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import helpers.upload_files


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('MOBILE PHONES', 'Mobile Phones'), ('COMPUTERS', 'Computers'), ('ELECTRONICS', 'Electronics'), ('HOME_APPLIANCES', 'Home Appliances'), ('SECURITY', 'Security'), ('AUTOMOBILES', 'Automobiles'), ('FURNITURE', 'Furniture'), ('CLOTHING', 'Clothing'), ('SHOES', 'Shoes'), ('ACCESSORIES', 'Accessories'), ('SPORT', 'Sport'), ('FOOD', 'Food')], max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('other', models.CharField(blank=True, max_length=155, null=True)),
                ('origin', models.CharField(max_length=200)),
                ('certification', models.CharField(blank=True, max_length=155, null=True)),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.brand')),
            ],
        )
    ]
