# Generated by Django 4.2.2 on 2023-07-13 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='product',
            name='character',
        ),
        migrations.DeleteModel(
            name='Brand',
        ),
        migrations.DeleteModel(
            name='Character',
        ),
    ]
